### ISSUE TITLE
Is it possible to use external OAuth provider?

### ISSUE THREAD

**Issue by nelsonchen90** [sw-yx/react-netlify-identity#3]
Does this React wrapper support external oauth providers like the official library?

**Comment by sw-yx** [comment]
hey! do you mean https://github.com/netlify/gotrue-js supporting oauth providers? because i dont think it does. or what do you mean official library?

in general, for oauth providers that netlify doesn't support as a first class citizen, you'll have to use a serverless function: https://www.netlify.com/blog/2018/07/30/how-to-setup-serverless-oauth-flows-with-netlify-functions--intercom/

**Comment by nelsonchen90** [comment]
@sw-yx Hi! thanks for the reply!
I meant this https://github.com/netlify/netlify-identity-widget . it supports oauth providers like Google/github etc.

**Comment by sw-yx** [comment]
ahh. yeah it is possible, i just havent coded it yet 😅 we will have to port over this bunch of code: https://github.com/netlify/netlify-identity-widget/blob/ece08ed2a3653adcad87cf3998277362e362da60/src/state/store.js#L99-L119

**Comment by sw-yx** [comment]
cc @nelsonchen90 https://react-netlify-identity-widget.netlify.com/?#

**Comment by nelsonchen90** [comment]
@sw-yx thanks for the update!
