### ISSUE TITLE
isLoggedIn always false

### ISSUE THREAD

**Issue by YChebotaev** [sw-yx/react-netlify-identity#7]
After successfully confirm email with approach described [here](https://github.com/sw-yx/react-netlify-identity/issues/5#issuecomment-485454728), I'm trying to log in.

Then, when I enter email and password and invoke `loginUser` with them, I expect to `isLoggedIn` to be `true`.

But `isLoggedIn` flag always returns `false` for me.

How I can overcome this obstacle?

**Comment by sw-yx** [comment]
something has to be up with your implementation. have you seen how the demo works? how does your implementation defer?

**Comment by YChebotaev** [comment]
@sw-yx Your demo also not working properly: after page reload I lost all my authentication.

**Comment by sw-yx** [comment]
yeah thats because i havent updated to use this: https://github.com/sw-yx/react-netlify-identity/pull/2

should be a simple fix.

i'm sorry you're facing so much trouble - as the readme says this is not an official netlify project. even tho i'm a netlify employee i did this in my own time just because i'm a react fan. at this stage in the project's life i need people who can contribute their own bugfixes.

that said, i'm currently working on a new demo that uses react netlify identity. so this feedback -is- helpful and i will keep it in mind. i just dont want to promise i can solve your issue straight away esp when i can't see your repo.

**Comment by sw-yx** [comment]
hey @YChebotaev - so it was a simple error - i forgot to set the `remember` flag to true :) https://github.com/sw-yx/react-netlify-identity/commit/a8a8106c9317228848c349487b8626040bc5ebf0

now if you go to https://netlify-gotrue-in-react.netlify.com/dashboard and login and refresh, it persists. sorry for the bad demo. but thanks for reporting the problem.
